<a href="https://colab.research.google.com/github/sparsh2002/Advanced_Natural_Language_Processing/blob/master/Word_embedding_Techniques.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Word Embedding Techniques using Embedding Layer in Keras

In [1]:
### Libraries USed Tensorflow> 2.0  and keras

In [2]:
!pip install tensorflow-gpu

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
  Preparing metadata (setup.py) ... done
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for tensorflow-gpu
  Running setup.py clean for tensorflow-gpu
Failed to build tensorflow-gpu
  error: subprocess-exited-with-error
  
  × Running setup.py install for tensorflow-gpu did not run successfully.
  │ exit code: 1
  ╰─> See above for output.
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  Running setup.py install for tensorflow-gpu ... error
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> tensorflow-gpu

note: This is an issue with the package mentioned above, not pip.
hint: See above for outpu

In [3]:
import tensorflow as tf
print(tf.__version__)

2.11.0


In [4]:
##tensorflow >2.0
from tensorflow.keras.preprocessing.text import one_hot

In [5]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good']

In [6]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [7]:
### Vocabulary size
voc_size=500

#### One Hot Representation

In [8]:
onehot_repr=[one_hot(words,voc_size)for words in sent] 
print(onehot_repr)

[[223, 89, 131, 380], [223, 89, 131, 470], [223, 65, 131, 332], [376, 375, 320, 319, 195], [376, 375, 320, 319, 72], [489, 223, 19, 131, 181], [104, 223, 4, 319]]


### Word Embedding Represntation

In [9]:
from tensorflow.keras.layers import Embedding
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential

In [10]:
import numpy as np

In [11]:
## pre padding
sent_length=8
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[  0   0   0   0 223  89 131 380]
 [  0   0   0   0 223  89 131 470]
 [  0   0   0   0 223  65 131 332]
 [  0   0   0 376 375 320 319 195]
 [  0   0   0 376 375 320 319  72]
 [  0   0   0 489 223  19 131 181]
 [  0   0   0   0 104 223   4 319]]


In [12]:
## 10 feature dimesnions
dim=10


In [13]:
model=Sequential()
model.add(Embedding(voc_size,10,input_length=sent_length))
model.compile('adam','mse')

In [14]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             5000      
                                                                 
Total params: 5,000
Trainable params: 5,000
Non-trainable params: 0
_________________________________________________________________


In [15]:
##'the glass of milk',
embedded_docs[0]

array([  0,   0,   0,   0, 223,  89, 131, 380], dtype=int32)

In [16]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 215ms/step


array([[ 0.00116991, -0.00473101,  0.01906253, -0.02749264,  0.04559976,
         0.04431846,  0.00959443,  0.01506522,  0.03441376, -0.04995065],
       [ 0.00116991, -0.00473101,  0.01906253, -0.02749264,  0.04559976,
         0.04431846,  0.00959443,  0.01506522,  0.03441376, -0.04995065],
       [ 0.00116991, -0.00473101,  0.01906253, -0.02749264,  0.04559976,
         0.04431846,  0.00959443,  0.01506522,  0.03441376, -0.04995065],
       [ 0.00116991, -0.00473101,  0.01906253, -0.02749264,  0.04559976,
         0.04431846,  0.00959443,  0.01506522,  0.03441376, -0.04995065],
       [-0.03998123, -0.0465714 , -0.04351636, -0.03433656,  0.02199147,
         0.04985905,  0.03062903, -0.03597549, -0.00512433,  0.007722  ],
       [ 0.01476559, -0.0056456 ,  0.00956402, -0.00916693,  0.01861245,
         0.04169917,  0.01886079,  0.00286136, -0.01458663,  0.00568823],
       [ 0.00310203, -0.019775  , -0.02045685,  0.03055472, -0.01120303,
        -0.03369068,  0.01876106, -0.03203984

In [17]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 38ms/step
[[[ 0.00116991 -0.00473101  0.01906253 -0.02749264  0.04559976
    0.04431846  0.00959443  0.01506522  0.03441376 -0.04995065]
  [ 0.00116991 -0.00473101  0.01906253 -0.02749264  0.04559976
    0.04431846  0.00959443  0.01506522  0.03441376 -0.04995065]
  [ 0.00116991 -0.00473101  0.01906253 -0.02749264  0.04559976
    0.04431846  0.00959443  0.01506522  0.03441376 -0.04995065]
  [ 0.00116991 -0.00473101  0.01906253 -0.02749264  0.04559976
    0.04431846  0.00959443  0.01506522  0.03441376 -0.04995065]
  [-0.03998123 -0.0465714  -0.04351636 -0.03433656  0.02199147
    0.04985905  0.03062903 -0.03597549 -0.00512433  0.007722  ]
  [ 0.01476559 -0.0056456   0.00956402 -0.00916693  0.01861245
    0.04169917  0.01886079  0.00286136 -0.01458663  0.00568823]
  [ 0.00310203 -0.019775   -0.02045685  0.03055472 -0.01120303
   -0.03369068  0.01876106 -0.03203984 -0.03108386 -0.04917796]
  [ 0.03529928  0.01686594  0.03513077  0.03977809  0.04433

In [18]:
embedded_docs[0]

array([  0,   0,   0,   0, 223,  89, 131, 380], dtype=int32)

In [19]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 21ms/step
[[ 0.00116991 -0.00473101  0.01906253 -0.02749264  0.04559976  0.04431846
   0.00959443  0.01506522  0.03441376 -0.04995065]
 [ 0.00116991 -0.00473101  0.01906253 -0.02749264  0.04559976  0.04431846
   0.00959443  0.01506522  0.03441376 -0.04995065]
 [ 0.00116991 -0.00473101  0.01906253 -0.02749264  0.04559976  0.04431846
   0.00959443  0.01506522  0.03441376 -0.04995065]
 [ 0.00116991 -0.00473101  0.01906253 -0.02749264  0.04559976  0.04431846
   0.00959443  0.01506522  0.03441376 -0.04995065]
 [-0.03998123 -0.0465714  -0.04351636 -0.03433656  0.02199147  0.04985905
   0.03062903 -0.03597549 -0.00512433  0.007722  ]
 [ 0.01476559 -0.0056456   0.00956402 -0.00916693  0.01861245  0.04169917
   0.01886079  0.00286136 -0.01458663  0.00568823]
 [ 0.00310203 -0.019775   -0.02045685  0.03055472 -0.01120303 -0.03369068
   0.01876106 -0.03203984 -0.03108386 -0.04917796]
 [ 0.03529928  0.01686594  0.03513077  0.03977809  0.04433146 -0.00989125

In [20]:
### Assignment

sent=["The world is a better place",
      "Marvel series is my favourite movie",
      "I like DC movies",
      "the cat is eating the food",
      "Tom and Jerry is my favourite movie",
      "Python is my favourite programming language"
      ]